force-app/main/default/objects/BudgetRequest__c/BudgetRequest__c.object-meta.xml
<CustomObject>
    <label>Budget Request</label>
    <nameField>
        <displayFormat>RQ{000000}</displayFormat>
        <label>BudgetRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BudgetRequest__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BudgetRequest__c/fields/InactDate__c.field-meta.xml
<CustomField>
    <fullName>InactDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Inact Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BudgetRequest__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <defaultValue>&apos;Budget Request&apos;</defaultValue>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CBBudgetRequestCommunity.cls
public with sharing class CBBudgetRequestCommunity {

    @AuraEnabled(cacheable = false)
    public static List<Object> getCBRequests() {
        List<BudgetRequest__c> r = new List<BudgetRequest__c>();
        try {
            r = [
                    SELECT Id, Name, Title__c, InactDate__c, Description__c, Amount__c
                    FROM BudgetRequest__c
            ];
            return r;
        } catch (Exception e) {
            r.add(new BudgetRequest__c(Title__c = e.getMEssage()));
            return r;
        }
    }

    @AuraEnabled(cacheable = true)
    public static List<Object> getListOfRelatedFiles(String recordId) {
        List<ContentDocumentLink> r = new List<ContentDocumentLink>();
        try {
            r = [
                    SELECT Id,
                            ContentDocumentId,
                            ContentDocument.Title
                    FROM ContentDocumentLink
                    WHERE LinkedEntityId = 'a0H3t00000MMu5FEAT'
            ];
            return r;
        } catch (Exception e) {
            return null;
        }
    }

    @AuraEnabled
    public static String saveCBRequests(BudgetRequest__c request) {
        System.debug(request);
        upsert request;
        return 'Saved';
    }

    @AuraEnabled
    public static String deleteCBRequest(String recordId) {
        delete [SELECT Id FROM BudgetRequest__c WHERE Id = :recordId];
        return 'Deleted';
    }
}